version: "3.9"
services:
  nginx:
    image: nginx:latest
    depends_on:
      - backendx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx-config/:/etc/nginx/conf.d/:ro
  backendx:
    build: ./backend
    expose:
      - 3000
    environment:
      - "NODESERVER=from server"
